LANGUAGE_CODE=ina
LANGUAGE_ALPHA2=ia
LANGUAGE_NAME=Interlingua (International Auxiliary Language Association)
LANGUAGE_SCOPE=I
LANGUAGE_TYPE=C
TEXT_DIRECTION=auto
FONT=auto
TRANSLATION_STATUS=fallback
